import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.application.Platform.exit;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;
import java.io.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.Dimension;
import javax.sound.sampled.*;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Useer
 */
public class PredatorPrey extends javax.swing.JFrame implements ActionListener{
    private static Double[] x, y, t;
    private static double a, b, c, d, n;
    /**
     * Creates new form PredatorPrey
     */
    public PredatorPrey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        Color yellowhite1 = new Color(255, 250, 155);
        Color yellowhite2 = new Color(245, 255, 130);


        this.setSize(450, 350);
        this.setResizable(false);

        ImageIcon icon = new ImageIcon("icon.jpg");
        this.setIconImage(icon.getImage());
        
        this.setTitle("CS 131, Case Study 4A");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

        bgPane = new JLabel();
        bgPane.setIcon(new ImageIcon("predprey.jpg"));
        bgPane.setLayout(new BorderLayout());
        this.setContentPane(bgPane);

        calcButton = new JButton("Calculate (RK4)");
        calcButton.setForeground(Color.WHITE);
        calcButton.setOpaque(false);
        calcButton.setContentAreaFilled(false);

        showGraphsButton = new JButton("Show Graphs");
        showGraphsButton.setForeground(Color.WHITE);
        showGraphsButton.setOpaque(false);
        showGraphsButton.setContentAreaFilled(false);
        //

        populationLabel = new JLabel("Initial prey (x) and predator (y) populations: ");
        populationLabel.setForeground(Color.WHITE);

        abLabel = new JLabel("Prey growth (a) and destruction (b) rates: ");
        abLabel.setForeground(Color.WHITE);

        cdLabel = new JLabel("Predator death (c) and increase (d) rates: ");
        cdLabel.setForeground(Color.WHITE);

        tRangeLabel = new JLabel("Time range [start, end]: ");
        tRangeLabel.setForeground(Color.WHITE);

        intervalLabel= new JLabel("Interval: ");
        intervalLabel.setForeground(Color.WHITE);
        //

        initPreyText = new JTextField(4); initPreyText.setEditable(true); initPreyText.setBackground(yellowhite1);
        initPredText = new JTextField(4); initPredText.setEditable(true); initPredText.setBackground(yellowhite1);
        preyGroText = new JTextField(4); preyGroText.setEditable(true); preyGroText.setText("1.2");
        preyDestText = new JTextField(4); preyDestText.setEditable(true); preyDestText.setText("0.6");
        predDthText = new JTextField(4); predDthText.setEditable(true); predDthText.setText("0.8");
        predIncrText = new JTextField(4); predIncrText.setEditable(true); predIncrText.setText("0.3");
        tRange1Text = new JTextField(4); tRange1Text.setEditable(true); tRange1Text.setText("0"); 
        tRange2Text = new JTextField(4); tRange2Text.setEditable(true); tRange2Text.setText("30");
        intervalText = new JTextField(4); intervalText.setEditable(true); intervalText.setText("0.1");
        //

        Container c = this.getContentPane();
        c.setLayout(new BoxLayout(c, BoxLayout.PAGE_AXIS));

        //////////////////////////////////////////////////////////////LABELS

        // TITLE
        JPanel titlePanel = new JPanel(new GridBagLayout());
        titlePanel.setOpaque(false);

        titleLabel = new JLabel("Lotka-Volterra (Predator-Prey) Models");
        titleLabel.setFont(new Font(titleLabel.getFont().getName(), Font.ITALIC+Font.BOLD, 18));
        titleLabel.setForeground(yellowhite2);

        GridBagConstraints titlegbc = new GridBagConstraints();
        titlegbc.insets = new Insets(8, 8, 8, 8);

        titlegbc.gridx = 0;
        titlegbc.gridy = 0;
        titlePanel.add(titleLabel,titlegbc);

        this.add(titlePanel, BorderLayout.NORTH);
        // TITLE-END

        JPanel labelPanel = new JPanel(new GridBagLayout());
        labelPanel.setOpaque(false);
        GridBagConstraints labelgbc = new GridBagConstraints();
        labelgbc.insets = new Insets(5, 5, 5, 5);

        labelgbc.gridx = 1;
        labelgbc.gridy = 0;
        labelPanel.add(populationLabel,labelgbc);
        labelgbc.gridx = 2;
        labelgbc.gridy = 0;
        labelPanel.add(initPreyText,labelgbc);
        labelgbc.gridx = 3;
        labelgbc.gridy = 0;
        labelPanel.add(initPredText,labelgbc);
        //
        labelgbc.gridx = 1;
        labelgbc.gridy = 1;
        labelPanel.add(abLabel,labelgbc);
        labelgbc.gridx = 2;
        labelgbc.gridy = 1;
        labelPanel.add(preyGroText,labelgbc);
        labelgbc.gridx = 3;
        labelgbc.gridy = 1;
        labelPanel.add(preyDestText,labelgbc);
        //
        labelgbc.gridx = 1;
        labelgbc.gridy = 2;
        labelPanel.add(cdLabel,labelgbc);
        labelgbc.gridx = 2;
        labelgbc.gridy = 2;
        labelPanel.add(predDthText,labelgbc);
        labelgbc.gridx = 3;
        labelgbc.gridy = 2;
        labelPanel.add(predIncrText,labelgbc);
        //
        labelgbc.gridx = 1;
        labelgbc.gridy = 3;
        labelPanel.add(tRangeLabel,labelgbc);
        labelgbc.gridx = 2;
        labelgbc.gridy = 3;
        labelPanel.add(tRange1Text,labelgbc);
        labelgbc.gridx = 3;
        labelgbc.gridy = 3;
        labelPanel.add(tRange2Text,labelgbc);
        //
        labelgbc.gridx = 1;
        labelgbc.gridy = 4;
        labelPanel.add(intervalLabel,labelgbc);
        labelgbc.gridx = 2;
        labelgbc.gridy = 4;
        labelPanel.add(intervalText,labelgbc);
        //

        this.add(labelPanel,BorderLayout.CENTER);


        ///////////////////////////////////////////////////////////// BUTTON PANEL

        JPanel buttonPanel = new JPanel(new GridBagLayout());
        buttonPanel.setOpaque(false);
        GridBagConstraints buttonsgbc = new GridBagConstraints();
        buttonsgbc.insets = new Insets(10,15,15,10);

        buttonsgbc.gridx = 1;
        buttonsgbc.gridy = 0;
        calcButton.addActionListener(this);
        buttonPanel.add(calcButton, buttonsgbc);
        buttonsgbc.gridx = 2;
        buttonsgbc.gridy = 0;
        showGraphsButton.addActionListener(this);
        buttonPanel.add(showGraphsButton, buttonsgbc);

        this.add(buttonPanel, BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents
    public void actionPerformed(ActionEvent e) {
        String action = e.getActionCommand();
        if (action.equals("Calculate (RK4)")) {
            Double xinit = Double.parseDouble(initPreyText.getText());
            Double yinit = Double.parseDouble(initPredText.getText());
            a = Double.parseDouble(preyGroText.getText());
            b = Double.parseDouble(preyDestText.getText());
            c = Double.parseDouble(predDthText.getText());
            d = Double.parseDouble(predIncrText.getText());
            Double ti = Double.parseDouble(tRange1Text.getText());
            Double tf = Double.parseDouble(tRange2Text.getText());
            Double h = Double.parseDouble(intervalText.getText());
            
            
            n = (tf-ti)/h;
            
            driverRK4 rk = new driverRK4();
            rk.init(ti, tf, a, b, c, d, h, xinit, yinit);
            x = rk.getX();
            y = rk.getY();
            t = rk.getT();
        } else if (action.equals("Show Graphs")) {
            dispose();
            Graphs nc = new Graphs();
            nc.init(x, y, a, b, c, d, t, n);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PredatorPrey().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcButton, showGraphsButton;
    private javax.swing.JLabel titleLabel, populationLabel, abLabel, cdLabel, tRangeLabel, intervalLabel, bgPane;
    private javax.swing.JTextField initPreyText, initPredText, preyGroText, predDthText, preyDestText, predIncrText, tRange1Text, tRange2Text, intervalText;
    // End of variables declaration//GEN-END:variables
}

